<input 
    type="hidden"
    name="<?php echo $this->get_name(); ?>"
    value="<?php echo $this->value ?>"
    <?php echo ($this->readonly ? 'readonly' : ''); ?>
    <?php echo ($this->disabled ? 'disabled' : ''); ?>/>
<input 
    type="checkbox"
    id="<?php echo $this->id; ?>"
    <?php echo ($this->readonly ? 'readonly' : ''); ?>
    <?php echo ($this->disabled ? 'disabled' : ''); ?>
    <?php echo ($this->value === 'on' ? 'checked' : ''); ?>/>
<label for="<?php echo $this->id; ?>">
    <span class="label-on">ON</span>
    <span class="knob"></span>
    <span class="label-off">OFF</span>
</label>