<?php foreach($this->data as $value => $label): ?>
    <label>
        <input type="radio" 
                name="<?php echo $this->get_name(); ?>" 
                value="<?php echo $value ?>"
                <?php echo ($this->required ? 'aria-required="true"' : ''); ?>
                <?php echo ($this->readonly ? 'readonly' : ''); ?>
                <?php echo ($this->disabled ? 'disabled' : ''); ?>
                <?php echo ($this->value == $value ? 'checked' : ''); ?>/>
        <?php echo $label ?><br>
    </label>
<?php endforeach ?>