<div class="amarkal-ui-component amarkal-ui-component-text">
    <input 
        type="text"
        id="<?php echo $this->id; ?>"
        name="<?php echo $this->name; ?>"
        value="<?php echo $this->value; ?>"
        placeholder="<?php echo $this->placeholder; ?>"
        size="<?php echo $this->size; ?>"
        <?php echo ($this->required ? 'aria-required="true"' : ''); ?>
        <?php echo ($this->readonly ? 'readonly' : ''); ?>
        <?php echo ($this->disabled ? 'disabled' : ''); ?>/>
</div>